// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: time_line.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimelineGetFristPageResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Havenewmsg string                                `protobuf:"bytes,1,opt,name=Havenewmsg,proto3" json:"Havenewmsg,omitempty"`
	Data       []*TimelineGetFristPageResultDataItem `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *TimelineGetFristPageResult) Reset() {
	*x = TimelineGetFristPageResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_time_line_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimelineGetFristPageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineGetFristPageResult) ProtoMessage() {}

func (x *TimelineGetFristPageResult) ProtoReflect() protoreflect.Message {
	mi := &file_time_line_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineGetFristPageResult.ProtoReflect.Descriptor instead.
func (*TimelineGetFristPageResult) Descriptor() ([]byte, []int) {
	return file_time_line_proto_rawDescGZIP(), []int{0}
}

func (x *TimelineGetFristPageResult) GetHavenewmsg() string {
	if x != nil {
		return x.Havenewmsg
	}
	return ""
}

func (x *TimelineGetFristPageResult) GetData() []*TimelineGetFristPageResultDataItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type TimelineGetFristPageResultDataItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgidFull10 string `protobuf:"bytes,1,opt,name=MsgidFull10,proto3" json:"MsgidFull10,omitempty"`
	MsgidFull16 string `protobuf:"bytes,2,opt,name=MsgidFull16,proto3" json:"MsgidFull16,omitempty"`
	Msgid1      string `protobuf:"bytes,3,opt,name=Msgid1,proto3" json:"Msgid1,omitempty"`
	Msgid2      string `protobuf:"bytes,4,opt,name=Msgid2,proto3" json:"Msgid2,omitempty"`
	Msgtime     string `protobuf:"bytes,5,opt,name=Msgtime,proto3" json:"Msgtime,omitempty"`
	Wxid        string `protobuf:"bytes,6,opt,name=Wxid,proto3" json:"Wxid,omitempty"`
	Nickname    string `protobuf:"bytes,7,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Content     string `protobuf:"bytes,8,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *TimelineGetFristPageResultDataItem) Reset() {
	*x = TimelineGetFristPageResultDataItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_time_line_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimelineGetFristPageResultDataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineGetFristPageResultDataItem) ProtoMessage() {}

func (x *TimelineGetFristPageResultDataItem) ProtoReflect() protoreflect.Message {
	mi := &file_time_line_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineGetFristPageResultDataItem.ProtoReflect.Descriptor instead.
func (*TimelineGetFristPageResultDataItem) Descriptor() ([]byte, []int) {
	return file_time_line_proto_rawDescGZIP(), []int{1}
}

func (x *TimelineGetFristPageResultDataItem) GetMsgidFull10() string {
	if x != nil {
		return x.MsgidFull10
	}
	return ""
}

func (x *TimelineGetFristPageResultDataItem) GetMsgidFull16() string {
	if x != nil {
		return x.MsgidFull16
	}
	return ""
}

func (x *TimelineGetFristPageResultDataItem) GetMsgid1() string {
	if x != nil {
		return x.Msgid1
	}
	return ""
}

func (x *TimelineGetFristPageResultDataItem) GetMsgid2() string {
	if x != nil {
		return x.Msgid2
	}
	return ""
}

func (x *TimelineGetFristPageResultDataItem) GetMsgtime() string {
	if x != nil {
		return x.Msgtime
	}
	return ""
}

func (x *TimelineGetFristPageResultDataItem) GetWxid() string {
	if x != nil {
		return x.Wxid
	}
	return ""
}

func (x *TimelineGetFristPageResultDataItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *TimelineGetFristPageResultDataItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_time_line_proto protoreflect.FileDescriptor

var file_time_line_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x7e, 0x0a, 0x1a, 0x54,
	0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x73, 0x74, 0x50,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x48, 0x61, 0x76,
	0x65, 0x6e, 0x65, 0x77, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x48,
	0x61, 0x76, 0x65, 0x6e, 0x65, 0x77, 0x6d, 0x73, 0x67, 0x12, 0x40, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x47, 0x65, 0x74, 0x46, 0x72,
	0x69, 0x73, 0x74, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0xfc, 0x01, 0x0a, 0x22,
	0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x73, 0x74,
	0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x69, 0x64, 0x46, 0x75, 0x6c, 0x6c, 0x31,
	0x30, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4d, 0x73, 0x67, 0x69, 0x64, 0x46, 0x75,
	0x6c, 0x6c, 0x31, 0x30, 0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x69, 0x64, 0x46, 0x75, 0x6c,
	0x6c, 0x31, 0x36, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4d, 0x73, 0x67, 0x69, 0x64,
	0x46, 0x75, 0x6c, 0x6c, 0x31, 0x36, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x73, 0x67, 0x69, 0x64, 0x31,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x73, 0x67, 0x69, 0x64, 0x31, 0x12, 0x16,
	0x0a, 0x06, 0x4d, 0x73, 0x67, 0x69, 0x64, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x4d, 0x73, 0x67, 0x69, 0x64, 0x32, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x74, 0x69, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x57, 0x78, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x57, 0x78, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f,
	0x69, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_time_line_proto_rawDescOnce sync.Once
	file_time_line_proto_rawDescData = file_time_line_proto_rawDesc
)

func file_time_line_proto_rawDescGZIP() []byte {
	file_time_line_proto_rawDescOnce.Do(func() {
		file_time_line_proto_rawDescData = protoimpl.X.CompressGZIP(file_time_line_proto_rawDescData)
	})
	return file_time_line_proto_rawDescData
}

var file_time_line_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_time_line_proto_goTypes = []interface{}{
	(*TimelineGetFristPageResult)(nil),         // 0: protobuf.TimelineGetFristPageResult
	(*TimelineGetFristPageResultDataItem)(nil), // 1: protobuf.TimelineGetFristPageResultDataItem
}
var file_time_line_proto_depIdxs = []int32{
	1, // 0: protobuf.TimelineGetFristPageResult.Data:type_name -> protobuf.TimelineGetFristPageResultDataItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_time_line_proto_init() }
func file_time_line_proto_init() {
	if File_time_line_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_time_line_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimelineGetFristPageResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_time_line_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimelineGetFristPageResultDataItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_time_line_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_time_line_proto_goTypes,
		DependencyIndexes: file_time_line_proto_depIdxs,
		MessageInfos:      file_time_line_proto_msgTypes,
	}.Build()
	File_time_line_proto = out.File
	file_time_line_proto_rawDesc = nil
	file_time_line_proto_goTypes = nil
	file_time_line_proto_depIdxs = nil
}
